### ISSUE TITLE
Error when compiling for production

### ISSUE THREAD

**Issue by tproenca** [fknop/angular-breakpoints#2]
In development mode, it works fine. However, when I build for production I get the following error:
```
ERROR in Error encountered resolving symbol values statically. Function calls
are not supported. Consider replacing the function or lambda with a reference
to an exported function (position 42:36 in the original .ts file), resolving symbol
breakpointsProvider in [PROJECT_DIR]/node_modules/angular-breakpoints/index.ts
```

I'm using Angular 4.1.3 and Angular CLI 1.2.6 and using the following to build to prodution:
```
ng build --prod
```

**Comment by fknop** [comment]
Could you give it a try now ? I updated the function to be exported.

**Comment by tproenca** [comment]
Thanks Florian for making this update so fast.
It is showing a warning, but is compiling fine. 👍 

```
10% building modules 3/6 modules 3 active ...ules/bootstrap/dist/css/bootstrap.cssWarning:
Can't resolve all parameters for BreakpointsService in
<PROJECT>/node_modules/angular-breakpoints/index.ts: (?, ?). This will become an error in
Angular v5.x
```

**Comment by fknop** [comment]
Probably because there is a type annotation missing on the ngZone.

However, if you want a supported library by the angular team, I would recommend you use the `@angular/cdk` layout module which handle the same things. I will probably not keeping this up to date as an official angular module is doing the same thing.
